export const navigation = [
  { name: "Überblick", icon: "⌂" },
  { name: "Objekte", icon: "▦" },
  { name: "Einheiten", icon: "▥" },
  { name: "Mieter", icon: "♙" },
  { name: "Verträge", icon: "▤" },
  { name: "Zahlungen", icon: "€" },
  { name: "Betriebskosten", icon: "◫" },
  { name: "Dokumente", icon: "▱" },
  { name: "Termine & Aufgaben", icon: "◷" },
  { name: "Schäden & Vorgänge", icon: "△" },
  { name: "Dienstleister", icon: "♧" },
  { name: "Berichte", icon: "▤" },
  { name: "Einstellungen", icon: "⚙" },
];

export const initialCostItems = [
  { id: "abfall", name: "Abfallentsorgung", category: "Kalt-NK", amount: 640, key: "Wohnfläche (m²)", active: true },
  { id: "oberflaeche", name: "Oberflächenwasser", category: "Kalt-NK", amount: 210, key: "Wohnfläche (m²)", active: true },
  { id: "strassen", name: "Straßenreinigung", category: "Kalt-NK", amount: 150, key: "Wohnfläche (m²)", active: true },
  { id: "haftpflicht", name: "Gebäudehaftpflichtversicherung", category: "Kalt-NK", amount: 320, key: "Wohnfläche (m²)", active: true },
  { id: "leitungswasser", name: "Geb.-Vers. Leitungswasser/Sturm", category: "Kalt-NK", amount: 780, key: "Wohnfläche (m²)", active: true },
  { id: "glasbruch", name: "Glasbruchversicherung", category: "Kalt-NK", amount: 120, key: "Wohnfläche (m²)", active: true },
  { id: "strom_bel", name: "Strom (Beleuchtung)", category: "Kalt-NK", amount: 190, key: "Personen / Einheiten", active: true },
  { id: "garten", name: "Gartenpflege (Fremdfirma)", category: "Kalt-NK", amount: 850, key: "Wohnfläche (m²)", active: true },
  { id: "reinigung", name: "Reinigung (Fremdfirma)", category: "Kalt-NK", amount: 1200, key: "Wohnfläche (m²)", active: true },
  { id: "hausmeister", name: "Hausmeister (Fremdfirma)", category: "Kalt-NK", amount: 1500, key: "Wohnfläche (m²)", active: true },
  { id: "rwm", name: "Wartung RWM", category: "Kalt-NK", amount: 250, key: "Stück", active: true },
  { id: "heizkosten", name: "Heizkosten gemäß Fremdabrechner", category: "Warm-NK", amount: 2450, key: "Verbrauch / m²", active: true },
  { id: "ertrag_wasser", name: "Wasser / Rückerstattung", category: "Ertrag", amount: -60, key: "Wohnfläche (m²)", active: true },
  { id: "rwm_miete", name: "Rauchwarnmelder Miete", category: "Nicht umlagefähig", amount: 120, key: "Stück", active: true },
  { id: "reparaturen", name: "Reparaturen", category: "Nicht umlagefähig", amount: 450, key: "Anteile (1000stel)", active: true },
  { id: "konto", name: "Kontoführungskosten (Giro)", category: "Nicht umlagefähig", amount: 84, key: "Pauschal", active: true },
  { id: "direkt", name: "Kosten Direktzuordnung", category: "Nicht umlagefähig", amount: 0, key: "Pauschal", active: true },
  { id: "verwalter", name: "Verwalterentgelt", category: "Nicht umlagefähig", amount: 960, key: "Pauschal", active: true },
  { id: "verwalter_gem", name: "Verwalterentgelt (gem. Vereinb.)", category: "Nicht umlagefähig", amount: 0, key: "Pauschal", active: true },
];